### ISSUE TITLE
[Easy] scheduler.rs vs scheduler dir

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-services#840] opened 2020-05-04 07:55 UTC
There appears to be a scheduler file outside of scheduler directory.

**Comment by nlordell** [comment] 2020-05-04 10:10
Duplicate of #837

**Comment by bh2smith** [comment] 2020-05-04 10:26
> Duplicate of #837

These are different files in different parts of the same project. Just as long as both are taken care of. I might say this is "similar to" rather than duplicate.

**Closed** 2020-05-04 12:20 UTC
Labels: cleanup
