### ISSUE TITLE
Intermittent Snapp e2e test failure

### ISSUE THREAD

**Issue by nlordell** [gnosis/dex-services#467] opened 2020-01-29 15:41 UTC
The Snapp test seems to intermittently fail on "No state change detected after timeout". It is unclear why, but we should definitely fix this ASAP to improve confidence in our e2e tests.

**Comment by fleupold** [comment] 2020-01-29 19:51
Can you link an example failure and specify if this is the shell based test or the new rust based one?

**Comment by nlordell** [comment] 2020-01-29 19:56
It is a Rust based failure and unfortunately I hit the rebuild button and then it passes.

This was the job that had failed: https://travis-ci.com/gnosis/dex-services/jobs/281488445

I’ll rebuild it a few times and see if I can reproduce.

**Comment by fleupold** [comment] 2020-01-30 12:49
here is an instance: https://travis-ci.com/gnosis/dex-services/jobs/281737221

@bh2smith looks like this is related to the new snapp e2e tests. Could you take a look?

**Comment by fleupold** [comment] 2020-01-30 15:15
I might have found the cause. The `wait_for` implementation is not waiting for the future it's issuing.

**Comment by nlordell** [comment] 2020-01-30 16:21
Great catch @fleupold !

**Comment by bh2smith** [comment] 2020-01-30 17:09
>Could you take a look? 

Yes, I have been looking into this a bit as I go. Will look at your suggestion regarding `wait_for` stuff... although I could use a bit more context regarding "futures"

**Comment by bh2smith** [comment] 2020-01-30 21:49
I believe this was closed by #472

**Closed by bh2smith** 2020-01-30 21:49 UTC
