### ISSUE TITLE
fn retry_with_gas_price_increase -> do not resubmit tx, if gas price was not changed

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-services#853] opened 2020-05-10 06:43 UTC
This is regarding the following error:
https://gnosisinc.slack.com/archives/CQZBU9T5J/p1589080051000100

If the gas_cap has been reached, then we don't increase the nonce or the gas price anymore and we will get this error message.

Hence, the code should check  whether we had already increased the gas price to gas_cap already beforehand, and if this happened, then we should not try to resubmit

**Comment by fleupold** [comment] 2020-05-11 07:22
I integrated this into #825 so we can tackle the gas estimation improvements together.

**Comment by fleupold** [comment] 2020-05-11 09:58
From @nlordell 

> Regarding #853, maybe there was something else going on as well, since if the last gas price is the gas cap, then we do not resubmit the solution.

> I checked the logs and it looks like the solution was submitted twice, once with a gas price of 57500000001 and the second (and final) submission was with a gas price of 60000000000 (which is the gas cap). Unless I misunderstood the problem, then I believe it was working as intended.

> edit: Here is the start of the raw transaction data, formatted for easier readability:
```
// Tx #1:
0xf9074d
82 0218 // nonce
85 0d63445f01 // gas price
83 53ec60 // gas
94 6f400810b62df8e13fded51be75ff5393eaa841f // address
80 // value
... // solution data

// Tx #2:
0xf9074d
82 0218 // nonce
85 0df8475800 // gas price
83 53ec60 // gas
94 6f400810b62df8e13fded51be75ff5393eaa841f // address
80 // value
... // solution data
```

**Comment by fleupold** [comment] 2020-05-11 10:04
This might be a bug in the ethereum client:

I checked the openethereum code and the error seems to be coming from here: https://github.com/openethereum/openethereum/blob/748a8e384d06b7c963b34456b0bd04e5d02bba29/rpc/src/v1/helpers/errors.rs#L426-L431

This error gets only thrown in this codebase:

https://github.com/openethereum/openethereum/blob/748a8e384d06b7c963b34456b0bd04e5d02bba29/miner/src/pool/verifier.rs#L225-L239

which checks `should_reject_early`:

https://github.com/openethereum/openethereum/blob/748a8e384d06b7c963b34456b0bd04e5d02bba29/miner/src/pool/scoring.rs#L61-L67

I assume that our transaction was still considered to be local (in which case we always abort early). However, judging from the comment in the code the client should never call this method for local transactions:

> /// NOTE The method is never called for zero-gas-price transactions or local transactions
/// (such transactions are always considered to the pool and potentially rejected later on)

I will create an issue in the openethereum repository.

**Comment by fleupold** [comment] 2020-05-11 11:46
While trying to create an issue and reproducing this with a minimal viable example I found the line of code that causes this:

https://github.com/openethereum/openethereum/blob/748a8e384d06b7c963b34456b0bd04e5d02bba29/miner/src/pool/scoring.rs#L36-L44

We can only replace a tx if we are offering at least 12.5% more gas than the existing tx. I was able to reproduce locally using the following example (thanks to ethcontracts!). Note that sending the 2nd tx with 4.5 GWEI works (exactly 12.5% more than the original tx), but using 4.99GWEI fails:

```rust
async fn run() {
    let account = {
        let pk = env::var("PK").expect("PK is not set");
        let key: PrivateKey = pk.parse().expect("invalid PK");
        Account::Offline(key, Some(4))
    };
    let node_url = "https://node-openethereum.rinkeby.gnosisdev.com";

    let (eloop, http) = Http::new(&node_url).expect("transport failed");
    eloop.into_remote();
    let web3 = Web3::new(http);

    let mut instance = TokenOWL::deployed(&web3)
        .await
        .expect("locating deployed contract failed");
    instance.defaults_mut().from = Some(account);

    let mut method = instance
        .approve(Address::zero(), 100u32.into())
        .gas_price(GasPrice::Value(4_000_000_000u64.into()));
    method.tx.resolve = Some(ResolveCondition::Pending);
    method.send().await.expect("Error");
    println!("Sent first");
    instance
        .approve(Address::zero(), 100u32.into())
        .gas_price(GasPrice::Value(4_500_000_000u64.into()))
        .send()
        .await
        .expect("Failed");
    println!("Sent second");
}
```

**Comment by nlordell** [comment] 2020-05-11 13:47
That's some serious detective work :detective:

**Comment by fleupold** [comment] 2020-07-06 07:45
Closing in favor of #825

**Closed** 2020-07-06 07:45 UTC
